language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_script: 
 - echo 'date.timezone = "Europe/Oslo"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - curl -sS https://getcomposer.org/installer | php
 - php composer.phar install --dev
 - composer dump -o
script: 
 - vendor/bin/phpunit
