language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
 - echo 'date.timezone = "Europe/Oslo"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - composer install --dev -o -n

script:
 - mkdir -p build/logs
 - vendor/bin/phpcs --standard=PSR2 src
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v
 - bash <(curl -s https://codecov.io/bash)
